# Generated by Django 4.0 on 2021-12-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField(verbose_name='False')),
            ],
        ),
    ]
